version: "2"

linters:
  default: standard
  enable:
    - bodyclose
    - errorlint
    - gocritic
    - misspell
    - nolintlint
    - revive
    - rowserrcheck
    - sqlclosecheck
    - unconvert
    - whitespace
  settings:
    revive:
      rules:
        - name: exported
          disabled: true
  exclusions:
    rules:
      - path: _test\.go$
        linters:
          - errcheck
          - gocritic

formatters:
  enable:
    - gofmt
    - goimports
