package instagram

import (
	"regexp"
	"strings"
	"time"
)

// Sources a snapshot date can come from, in the order they are trusted.
const (
	// SourceDeclared is the export stating its own generation time.
	SourceDeclared = "declared in the export"
	// SourceArchive is the modification time recorded inside the archive.
	SourceArchive = "archive timestamp"
)

// generatedAtPattern matches the line newer exports carry, e.g.
// "Generated by example_account on Friday 12 April 2024 at 09:15 UTC".
//
// The weekday is skipped rather than parsed: it is redundant, and it is the
// part most likely to be localised even when the rest is not.
var generatedAtPattern = regexp.MustCompile(
	`(?i)generated by\s+\S+\s+on\s+(?:\w+\s+)?(\d{1,2}\s+\w+\s+\d{4})\s+at\s+(\d{1,2}:\d{2})`)

// ownerPattern captures the account an export was generated for, from the same
// line that carries the generation time.
var ownerPattern = regexp.MustCompile(`(?i)generated by\s+([A-Za-z0-9._]+)\s+on\b`)

// ownerFromMetadata reads the account name an export names as its owner.
func ownerFromMetadata(startHere []byte) (string, bool) {
	m := ownerPattern.FindStringSubmatch(textFromHTML(startHere))
	if m == nil {
		return "", false
	}
	handle := normalizeUsername(m[1])
	if !handlePattern.MatchString(handle) {
		return "", false
	}
	return handle, true
}

// takenAtFromMetadata reads the generation time an export states about itself.
func takenAtFromMetadata(startHere []byte) (time.Time, bool) {
	m := generatedAtPattern.FindStringSubmatch(textFromHTML(startHere))
	if m == nil {
		return time.Time{}, false
	}
	return parseBannerTime(m[1], m[2])
}

// FilenameDate reads the date Instagram puts in the archive name, as in
// instagram-someone-2024-10-23-tQF9URpZ.zip.
//
// Handles cannot contain a hyphen, so splitting on them is unambiguous. This is
// the least trustworthy source, because a browser or phone renames downloads
// freely, which is why it sits below the archive's own timestamps.
func FilenameDate(name string) (time.Time, bool) {
	base := strings.ToLower(strings.TrimSpace(name))
	base = strings.TrimSuffix(base, ".zip")

	m := archiveNamePattern.FindStringSubmatch(base)
	if m == nil {
		return time.Time{}, false
	}
	t, err := time.Parse("2006-01-02", m[2])
	if err != nil {
		return time.Time{}, false
	}
	return t.UTC(), true
}

// FilenameHandle reads the account name from the archive name.
func FilenameHandle(name string) (string, bool) {
	base := strings.ToLower(strings.TrimSpace(name))
	base = strings.TrimSuffix(base, ".zip")

	m := archiveNamePattern.FindStringSubmatch(base)
	if m == nil {
		return "", false
	}
	handle := normalizeUsername(m[1])
	if !handlePattern.MatchString(handle) {
		return "", false
	}
	return handle, true
}

// archiveNamePattern captures the handle and date from an export's file name.
var archiveNamePattern = regexp.MustCompile(`^instagram-([a-z0-9._]+)-(\d{4}-\d{2}-\d{2})-[a-z0-9]+$`)
