package tracker_test

import (
	"archive/zip"
	"bytes"
	"context"
	"strings"
	"testing"
	"time"

	"github.com/williamokano/insta-follower-tracker/internal/store"
	"github.com/williamokano/insta-follower-tracker/internal/tracker"
)

// namedZip builds an export whose summary page names the account it belongs to,
// the way a real download does.
func namedZip(t *testing.T, owner string, taken time.Time, usernames ...string) []byte {
	t.Helper()

	var buf bytes.Buffer
	zw := zip.NewWriter(&buf)
	write := func(name string, body []byte) {
		w, err := zw.CreateHeader(&zip.FileHeader{Name: name, Method: zip.Deflate, Modified: taken})
		if err != nil {
			t.Fatalf("create %s: %v", name, err)
		}
		if _, err := w.Write(body); err != nil {
			t.Fatalf("write %s: %v", name, err)
		}
	}

	summary := "<!DOCTYPE html><html><body><div>About your download</div>" +
		"<div>Generated by " + owner + " on Friday 12 April 2024 at 09:15 UTC</div>" +
		"</body></html>"

	write("start_here.html", []byte(summary))
	write("connections/followers_and_following/followers_1.json", exportJSON(t, usernames...))
	if err := zw.Close(); err != nil {
		t.Fatalf("close zip: %v", err)
	}
	return buf.Bytes()
}

// TestAccountIsReadFromTheArchiveFileName is the common case: a download
// straight from Instagram carries the handle in its name.
func TestAccountIsReadFromTheArchiveFileName(t *testing.T) {
	svc, st, _ := newService(t)

	up := upload(t, svc, "", "instagram-example_account-2024-10-23-tQF9URpZ.zip",
		exportJSON(t, "alice", "bob"))

	if up.AccountHandle != "example_account" {
		t.Fatalf("account = %q, want example_account read from the file name", up.AccountHandle)
	}
	if up.Status != store.StatusCompleted {
		t.Fatalf("status = %q (%s)", up.Status, up.ErrorMessage)
	}

	if _, err := st.AccountByHandle(context.Background(), "example_account"); err != nil {
		t.Fatalf("the account should have been created: %v", err)
	}
}

// TestAccountIsReadFromTheArchiveWhenRenamed covers a file whose name was
// rewritten on the way in, which browsers and phones do freely.
func TestAccountIsReadFromTheArchiveWhenRenamed(t *testing.T) {
	svc, _, _ := newService(t)

	up := upload(t, svc, "", "download (3).zip",
		namedZip(t, "example_account", day(2024, time.April, 12), "alice", "bob"))

	if up.AccountHandle != "example_account" {
		t.Fatalf("account = %q, want example_account read from inside the archive", up.AccountHandle)
	}
	if up.Status != store.StatusCompleted {
		t.Fatalf("status = %q (%s)", up.Status, up.ErrorMessage)
	}
}

// TestSuppliedAccountWinsOverTheExport keeps the person uploading in charge,
// which matters when a handle has been renamed since the export was taken.
func TestSuppliedAccountWinsOverTheExport(t *testing.T) {
	svc, _, _ := newService(t)

	up := upload(t, svc, "my.new.handle", "instagram-my_old_handle-2024-10-23-tQF9URpZ.zip",
		exportJSON(t, "alice"))

	if up.AccountHandle != "my.new.handle" {
		t.Fatalf("account = %q, want the handle that was supplied", up.AccountHandle)
	}
}

// TestUndeterminableAccountIsRejectedClearly: when nothing names the account,
// say so rather than invent one.
func TestUndeterminableAccountIsRejectedClearly(t *testing.T) {
	svc, _, _ := newService(t)

	_, err := svc.Accept(context.Background(), "", "download.zip",
		bytes.NewReader(exportJSON(t, "alice")), tracker.AcceptOptions{})
	if err == nil {
		t.Fatal("expected an upload with no determinable account to be rejected")
	}
	if !strings.Contains(err.Error(), "which account") {
		t.Fatalf("error should explain what is missing, got: %v", err)
	}
}

// TestRejectedUploadLeavesNothingBehind: the file is written before the account
// is known, so a failure to resolve one must not strand it.
func TestRejectedUploadLeavesNothingBehind(t *testing.T) {
	svc, st, uploadDir := newService(t)
	ctx := context.Background()

	_, err := svc.Accept(ctx, "", "download.zip",
		bytes.NewReader(exportJSON(t, "alice")), tracker.AcceptOptions{})
	if err == nil {
		t.Fatal("expected rejection")
	}

	leftovers := countFiles(t, uploadDir)
	if leftovers != 0 {
		t.Fatalf("rejected upload left %d file(s) on disk", leftovers)
	}

	pending, err := st.PendingCount(ctx)
	if err != nil {
		t.Fatalf("pending: %v", err)
	}
	if pending != 0 {
		t.Fatalf("rejected upload queued %d row(s)", pending)
	}
}

// TestStoredFileLandsUnderItsAccount checks the upload is moved out of staging
// once the account is known, so the layout on disk stays browsable.
func TestStoredFileLandsUnderItsAccount(t *testing.T) {
	svc, _, uploadDir := newService(t)

	upload(t, svc, "", "instagram-example_account-2024-10-23-tQF9URpZ.zip",
		exportJSON(t, "alice"))

	if n := countFilesIn(t, uploadDir, "example_account"); n != 1 {
		t.Fatalf("files under the account directory = %d, want 1", n)
	}
	if n := countFilesIn(t, uploadDir, ".incoming"); n != 0 {
		t.Fatalf("staging still holds %d file(s)", n)
	}
}
